// Modules-Encapsulated code(only share minimum)
//Common JS, everyfile is module(By default)
const names=require('./3-names')
const sayHi=require('./4-utils')
const data=require('./5-alternative-flavour')
require('./6-mind-grenade')
sayHi('susan')
sayHi(names.john)
sayHi(names.peter)